### ISSUE TITLE
test.py was not worked as expected

### ISSUE THREAD

**Issue by Sumadera2714** [DegardinBruno/human_activity_anomaly_IJCB20#14]
When I run the test.py the program cannot work successfully . It hints me  that:
Using TensorFlow backend.
2022-04-10 11:18:38.853189: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2022-04-10 11:18:41.601766: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-04-10 11:18:41.602005: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-10 11:18:41.605862: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-DNTLE7D
2022-04-10 11:18:41.606161: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-DNTLE7D
2022-04-10 11:18:41.606971: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "D:/human-self-learning-anomaly-master/human-self-learning-anomaly-master/test.py", line 47, in <module>
    test(opt.weak_model, opt.strong_model, opt.model_iteration, not opt.val, opt.path_test, opt.path_test_note, pred_gap, opt.features)
  File "D:/human-self-learning-anomaly-master/human-self-learning-anomaly-master/test.py", line 14, in test
    notes, scores = WC.test(flag_test, iteration, path_test, path_test_note, pred_gap) if model_weak else SC.test(flag_test, iteration, path_test, path_test_note, num_features)
  File "D:\human-self-learning-anomaly-master\human-self-learning-anomaly-master\strong_classifier.py", line 294, in test
    read_annotation(test_notes, 1)                                           # Load test/val annotations
  File "D:\human-self-learning-anomaly-master\human-self-learning-anomaly-master\strong_classifier.py", line 207, in read_annotation
    notes_test.append(int(row[0])) if flag_test else notes_train.append(int(row[0]))
ValueError: invalid literal for int() with base 10: '\ufeff'
Can you give me some help?

**Comment by DegardinBruno** [comment]
There are a few warnings and errors here:
> Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found

You are missing some Cuda library for GPU use.

>notes_test.append(int(row[0])) if flag_test else notes_train.append(int(row[0]))
ValueError: invalid literal for int() with base 10: '\ufeff'

I think you have a misplaced character in your test annotation file, so when he tries to make sure it's an int value, he can't due to that "invalid literal".

**Comment by Sumadera2714** [comment]
> There are a few warnings and errors here:
> 
> > Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
> 
> You are missing some Cuda library for GPU use.
> 
> > notes_test.append(int(row[0])) if flag_test else notes_train.append(int(row[0]))
> > ValueError: invalid literal for int() with base 10: '\ufeff'
> 
> I think you have a misplaced character in your test annotation file, so when he tries to make sure it's an int value, he can't due to that "invalid literal".

hmm， I really don't know these files in the dict "annoation/weak(strong)" how to describe them. Can u introduce them simplely? Such as the test.csv, Should I put the one of the video name of the UBI datasets ? And the test_note I really don't know what comment should in it .
